---
- name: Ensure swap file exists.
  ansible.builtin.command: >
    {{ swap_file_create_command }}
    creates='{{ swap_file_path }}'
  register: swap_file_create

- name: Set permissions on swap file.
  ansible.builtin.file:
    path: "{{ swap_file_path }}"
    owner: root
    group: root
    mode: 0600

- name: Make swap file if necessary.
  ansible.builtin.command: mkswap {{ swap_file_path }} # noqa: no-handler
  when: swap_file_create is changed
  register: mkswap_result
  changed_when: true

- name: Run swapon on the swap file.
  ansible.builtin.command: swapon -o {{ swap_options }} {{ swap_file_path }}
  when:
    - mkswap_result is changed
    - not swap_test_mode
  changed_when: true

- name: Set swappiness.
  ansible.posix.sysctl:
    name: vm.swappiness
    value: "{{ swap_swappiness }}"
    state: present
